title: DejingMa's BLOG
author: DejingMa
description: 

# markdown: redcarpet
highlighter: null
permalink: /:title

url:
baseurl: /DejingMa's BLOG

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed