title: DejingMa's Blog
author: DejingMa
description: 

# markdown: redcarpet
highlighter: null
permalink: /:title

url:
baseurl: /blog

redcarpet:
  extensions: [strikethrough, tables]

sass:
  sass_dir: public/css
  style: :compressed